version: "3.8"
services:
  wg-easy:
    environment:
      - WG_HOST=192.168.0.15
      - PASSWORD=Franci78
      
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - .:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
