---
title: "Homer Theme"
subtitle: "Walkx"
logo: "logo.png"

header: false
footer: false 

stylesheet:
  - "assets/custom.css"

columns: "3" # You can change this to any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "#fff5f2"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper-light.jpeg" # Change wallpaper.jpeg to the name of your own custom wallpaper!
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "#020204"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper.jpeg"

services:
  - name: "//Server"
    icon: "fas fa-cloud"
    items:
      - name: "OMV"
        logo: "assets/icons/openmediavault.png"
        subtitle: "OpenMedaiVault"
        tag: "9090"
        url: "http://192.168.0.15:9090/"
      - name: "Portainer"
        logo: "assets/icons/portainer.png"
        subtitle: "Docker Container Manager"
        tag: "9000"
        url: "http://192.168.0.15:9000/"
      - name: "Nginx Proxgy Manager"
        logo: "assets/icons/nginxproxymanager.png"
        subtitle: "Reverse Proxy Manager"
        tag: "81"
        url: "http://192.168.0.15:81/"
  - name: "//Tools"
    icon: "fas fa-tools"
    items: 
      - name: "Wireguard"
        logo: "assets/icons/wireguard.png"
        subtitle: "VPN"
        tag: "51821"
        url: "http://192.168.0.15:51821"
      - name: "Duplicati"
        logo: "assets/icons/duplicati.png"
        subtitle: "Backup manager"
        tag: "8200"
        url: "http://192.168.0.15:8200"
      - name: "Focalboard"
        logo: "assets/icons/focalboard.png"
        subtitle: "Notes"
        tag: "22300"
        url: "http://192.168.0.15:22300"
  - name: "//media"
    icon: "fas fa-film"
    items:
      - name: "Jellyfin"
        logo: "assets/icons/jellyfin.png"
        subtitle: "Media Center"
        tag: "8096"
        url: "http://192.168.0.15:8096"
      - name: "Transmission"
        logo: "assets/icons/transmission.png"
        subtitle: "Torrent Download Client"
        tag: "9099"
        url: "http://192.168.0.15:9099"
