---
version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=admin #optional
      - PASS=admin #optional
    volumes:
      - /portainer/Files/AppData/Config/library/Transmission/config:/config
      - /path/to/downloads:/downloads
      - /portainer/Files/AppData/Config/library/Transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
