---
version: "2.1"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /portainer/Files/AppData/Config/library/Syncthing/config:/config
      - /portainer/Files/AppData/Config/library/Syncthing/data1:/data1
      - /portainer/Files/AppData/Config/library/Syncthing/data2:/data2
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
