---
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=password #optional
      - SUDO_PASSWORD=password #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /portainer/Files/AppData/Config/library/Homer:/config/workspace/homer
      - /portainer/Files/AppData/Config/library/CodeServer:/config
    ports:
      - 8443:8443
    restart: unless-stopped
