version: '3.3'
    
services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - /portainer/Files/AppData/Config/library/Authelia:/config
    ports:
      - 9091:9091
    environment:
      - TZ=Europe/Zagreb
